config/routes.rb
Weed::Application.routes.draw do

  root to: 'app#user_submit'
  post '/submit' => 'app#submit'
  get '/results' => 'app#results'
  #resources :votes

  get '/login' => 'app#login'
  post '/login' => 'app#process_login'

  get '/moderate' => 'app#moderate'
  post '/approve_story/:id' => 'app#approve_story', as: :approve_story
  post '/unapprove_story/:id' => 'app#unapprove_story', as: :unapprove_story

end

app/models/vote.rb
class Vote < ActiveRecord::Base

	validates :checkboxes, length: { minimum: 2 } # stored as a CSV string
	validates :support,    length: { minimum: 2 } # stored as "Yes" or "No"
	validates :story,      length: { maximum: 300 }

	def segment_values
		["Yes", "No"]
	end

	def checkbox_values
		[
			"Lazy",
			"Burnout",
			"Gardening",
			"Drug",
			"Every Day",
			"Taco Bell",
			"Cliff Harris",
			"Anxiety",
			"Drug Test",
			"Medicinal",
			"Calming"
		]	
	end

end

app/controllers/app_controller.rb
class AppController < ApplicationController
  def user_submit  	
  	@vote = Vote.new
  	@form_endpoint = ENV['FORM_ENDPOINT']
  	raise "Must specific FORM_ENDPOINT as ENV variable." if @form_endpoint.nil?
  end

  def submit
    user = cookies.permanent.signed[:emg_id1]
    vote = Vote.where(user: user).first || Vote.new(user: user)

    puts(params.inspect)

    vote.support = params[:support].try(:first)
    vote.story = params[:story]
    vote.story_approved = false
    vote.checkboxes = params[:checkboxes].join(",") rescue nil
    
    if vote.save  	
  		redirect_to '/results?review=t'
  	else
  		render action: 'user_submit'
  	end
  end

  def results
  	@stories = Vote.where(story_approved: true).order('created_at DESC')

  	@categories = Vote.new.checkbox_values
    @user_distrubution = Vote.pluck(:support).inject({}){ |obj, item|
      obj[item] ||= 0
      obj[item] += 1
      obj
    }.map{|key, val|
      {segment: key, count: val}
    }

  	@votes = Vote.all.flat_map{|vote|
  		vote.checkboxes.split(",").map{|checkbox|
  			{ support: vote.support || '?', vote: checkbox }
  		}
  	}.inject({}){|obj, item|
  		obj[item[:support]] ||= []
  		obj[item[:support]] << item[:vote]
  		obj
  	}.inject([]){|obj, item|
      segment = item.first
      values = item.last.inject({}){|obj, item|
        obj[item] ||= 0
        obj[item] += 1
        obj
      }.each{|category, count|
        obj << {segment: segment, category: category, count: count}
      }      
      obj
    }
  

  end

  def login
  end

  def process_login
    if params[:password] == ENV['PASSWORD']
      cookies.permanent.signed[:emg_id1_isadmin] = true
      redirect_to '/moderate'
    else
      render text: "Nope."
    end 
  end

  def moderate
    if cookies.permanent.signed[:emg_id1_isadmin] != true
      raise "not an admin"
    end

    @approved     = Vote.where(story_approved: true)
    @not_approved = Vote.where(story_approved: false).order('created_at DESC')

  end

  def approve_story
    if cookies.permanent.signed[:emg_id1_isadmin] != true
      raise "not an admin"
    end

    vote = Vote.find(params[:id])
    vote.story_approved = true
    vote.save
    redirect_to '/moderate'

  end

  def unapprove_story
    if cookies.permanent.signed[:emg_id1_isadmin] != true
      raise "not an admin"
    end

    vote = Vote.find(params[:id])
    vote.story_approved = false
    vote.save
    redirect_to '/moderate'

  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter do 
	if cookies.permanent.signed[:emg_id1].nil?
		cookies.permanent.signed[:emg_id1] = "#{Time.now.utc.to_f};#{SecureRandom.uuid}"
	end
  end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
  end

  # GET /votes/new
  def new
    @vote = Vote.new
  end

  # GET /votes/1/edit
  def edit
  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new(vote_params)

    respond_to do |format|
      if @vote.save
        format.html { redirect_to @vote, notice: 'Vote was successfully created.' }
        format.json { render action: 'show', status: :created, location: @vote }
      else
        format.html { render action: 'new' }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votes/1
  # PATCH/PUT /votes/1.json
  def update
    respond_to do |format|
      if @vote.update(vote_params)
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote.destroy
    respond_to do |format|
      format.html { redirect_to votes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      params.require(:vote).permit(:user, :checkboxes, :story, :story_approved)
    end
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/app/login.html.erb
<%= form_tag('/login') %>
<input name="password"></input>
</form>

app/views/app/moderate.html.erb
<style>
body {
	background: #FFF !important;
}
</style>

<div class="col">
<h2>Not Approved</h2>
<% @not_approved.each do |not_approved| %>
	<div class="admin-story">
		<p><%= not_approved.story %></p>
		<%= link_to "approve this", approve_story_path(not_approved.id), method: :post %>
	</div>
<% end %>
</div>

<div class="col">
<h2>Approved</h2>
<% @approved.each do |approved| %>
	<div class="admin-story">
		<p><%= approved.story %></p>
		<%= link_to "unapprove this", unapprove_story_path(approved.id), method: :post %>
	</div>
<% end %>
</div>

app/views/app/results.html.erb
<script>

segments = ["Yes", "No"];
user_distrubution = <%= raw JSON.pretty_generate @user_distrubution %>;
categories = <%= raw JSON.pretty_generate @categories %>;
votes = <%= raw JSON.pretty_generate @votes %>;

var render = function(animate) {


	var margin = {top: 0, right: 10, bottom: 20, left: 10},
      width = $(window).width() - margin.left - margin.right - 20,
      height = 600 - margin.top - margin.bottom;
	

    $('.vis .inner').html('') //ugz
	var stage = d3.select('.vis .inner').append('svg')		
		.attr('width', width + margin.left + margin.right)
	    .attr('height', height + margin.top + margin.bottom)
	  .append('g')
	    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");
	    

	 var x0 = Math.max(
	 	-d3.min(votes, function(d) { return d.count }), 
	 	 d3.max(votes, function(d) { return d.count })
	 );

	 var x = d3.scale.linear()
    	.domain([-x0, x0])
    	.range([width, 0])
    	.nice();

	var y = d3.scale.ordinal()
    	.rangeRoundBands([0, height], .1)
    	.domain(categories);

    var xAxis = d3.svg.axis()
    	.scale(x)
    	.orient("bottom");

    var bar = stage.selectAll('.bar')
      .data(votes)
    .enter().append("rect")
      .attr("class", "bar")
      .attr("x", function() { return x(0) })
      .attr("y", function(d, i) { return y(d.category) })      
      .attr("height", y.rangeBand())
      .style('fill', function(d) {
      	if (d.segment === 'Yes') {
      		return '#666666';
      	} else {
      		return '#515151';
      	}
      })
      .attr("width", 0);

    var bar_transition;
    if (animate === true) {
		bar_transition = bar.transition().duration(1500)
	} else {
		bar_transition = bar;
	}

	bar_transition.attr("x", function(d, i) {       	
	  	if (d.segment === "No") {
	  		return x(d.count)
	  	} else {
	  		return x(0)
	  	}      	
	  }) 
	  .attr("width", function(d) { 
	  	var count = d.count;
	  	if (d.segment === "No") {
	  		count = -count;
	  	}
	  	return Math.abs(x(count) - x(0));
	  })
    
    stage.selectAll('.label')
      .data(votes)
    .enter().append("text")
      .text(function(d, i) { return d.category })
      .attr('class', 'label')
      .attr('x', function(d, i) { return x(0) + 10 })
      .attr('y', function(d, i) { return y(d.category) })
      .attr('dy', 28)

     stage.append('g')
       .attr("class", "x axis")     
       .attr("transform", "translate(0, " + height + ")")
       .call(xAxis);
    
}

$(document).ready(function() {
	render(true);
	$(window).resize(function() {
		render(false);
	});
});

</script>

<div class="logo" style="margin-top:70px;padding-bottom:20px;">
	<a href="http://dailyemerald.com"><%= image_tag "logo.png" %></a>
</div>

<% if params[:review] == 't' %>
	<h3 class="in-review">Your story is being reviewed.</h3>
<% end %>

<div class="story-wrapper results-header">
	<h1>The results</h1>
	<h3 style="margin:30px 0">(Just arriving? <a href="/" class="">Submit your story</a>.)</h3>
	<iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fweed.dailyemerald.com%2Fresults&amp;width=200&amp;layout=button_count&amp;action=like&amp;show_faces=true&amp;share=true&amp;height=21&amp;appId=300474393462938" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:200px; height:21px;" allowTransparency="true"></iframe>
</div>

<div class="vis">
	<div class="label left">DON'T<br>SUPPORT</div>
	<div class="label right">SUPPORT</div>
	<div class="inner"></div>
</div>

<div class="story-wrapper">

	<h2><%= @stories.count %> stories</h2>

	<% @stories.each do |story| %>
		<div class="story">
			<span>“<%= story.story %>”</span><br>
			<small>Supports legalization? <b><%= story.support %></b></small> &bull;
			<small><%= story.created_at.strftime("%b %e, %l:%M %p") %></small>

		</div>
	<% end %>
</div>

app/views/app/submit.html.erb
<h1>App#submit</h1>
<p>Find me in app/views/app/submit.html.erb</p>

app/views/app/user_submit.html.erb
<div class="wrapper">
		
		<div class="logo">
			<a href="http://dailyemerald.com"><%= image_tag "logo.png" %></a>
		</div>

		<div class="intro">
			<h1>Weed diaries</h1>
			<p>Come November, Oregonians will ask themselves once again: Should recreational marijuana be legal? A 2012 measure to legalize the green was shot down by Oregon voters, but Colorado and Washington managed to make it happen. Will this year yield a different result? </p>

			<p>Help lead the conversation and let us know your thoughts on its legalization.</p>
		</div>
		
		<%= form_tag(@form_endpoint) %>

			<div class="question">
				<h2>Are you for the legalization of recreational marijuana?</h2>
				<div class="segment">
					<% ["Yes", "No"].each do |value| %>
						<div class="answer">
							<label><%= radio_button("support", nil, value) %> <%= value %></label>
						</div>			
					<% end %>
				</div>				
			</div>

			<div class="question">
				<h2>Which of these words come to mind when you hear the word “weed.” (Check all that apply.)</h2>
				<% @vote.checkbox_values.each do |value| %>		
					<div class="answer">
						<label><%= check_box_tag("checkboxes[]", value) %> <%= value %></label>
					</div>
				<% end %>				
			</div>

			<div class="question">
				<h2>Whether the green is not your thing or you blaze like Snoop Dogg, tell us the experience with marijuana that shaped your view the most. Be specific. (optional)</h2>
				<div class="answer">
					<%= text_area_tag "story", nil, rows: 5, cols: 40, class: "story-textarea" %><label class="story-textarea-label">Characters Remaining: <span class="char-count">300</span></label>					
				</div>
			</div>  

			<input type="submit" class="submit-button">
			
		</form>

		
</div><!-- .wrapper -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Weed diaries | Emerald Media Group</title>
  <meta charset="utf8">
  <meta name="viewport" content="width=device-width, inital-scale=1, maximum-scale=1, user-scalable=no, minimal-ui">
  <script type="text/javascript" src="//use.typekit.net/gpi1aid.js"></script>
  <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta property="fb:admins" content="100001785043323" />
  <meta property="fb:app_id" content="197312536953017" />
  <meta property="og:title" content="Weed diaries" />
  <meta property="og:description" content="Come November, Oregonians will ask themselves once again: Should recreational marijuana be legal? A 2012 measure to legalize the green was shot down by Oregon voters, but Colorado and Washington managed to make it happen. Will this year yield a different result?" />
  <meta property="og:url" content="http://weed.dailyemerald.com/results" />
  <meta property="og:type" content="website" />
  <meta property="og:image" content="http://i.imgur.com/nkfhNvK.png" />
</head>
<body>

<%= yield %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-50142839-1', 'dailyemerald.com');
  ga('send', 'pageview');

</script>

</body>
</html>

app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :checkboxes %><br>
    <%= f.text_field :checkboxes %>
  </div>
  <div class="field">
    <%= f.label :story %><br>
    <%= f.text_area :story %>
  </div>
  <div class="field">
    <%= f.label :story_approved %><br>
    <%= f.check_box :story_approved %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<h1>Listing votes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Checkboxes</th>
      <th>Story</th>
      <th>Story approved</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.user %></td>
        <td><%= vote.checkboxes %></td>
        <td><%= vote.story %></td>
        <td><%= vote.story_approved %></td>
        <td><%= link_to 'Show', vote %></td>
        <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
        <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New vote</h1>

<%= render 'form' %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @vote.user %>
</p>

<p>
  <strong>Checkboxes:</strong>
  <%= @vote.checkboxes %>
</p>

<p>
  <strong>Story:</strong>
  <%= @vote.story %>
</p>

<p>
  <strong>Story approved:</strong>
  <%= @vote.story_approved %>
</p>

<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>